### ISSUE TITLE
ProcessFailedException with subdomain

### ISSUE THREAD

**Issue by PDTRemi** [spatie/browsershot#141]
Hello i have this error when i try screenshort with subdomain.

This is my error:
```
ProcessFailedException
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/local.dev/lets-food-api/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"https:\/\/lets-food.pixel-agence.fr","action":"screenshot","options":{"path":"upload\/screenshots\/f6e41be0-d515-11e7-92e4-ad7f2073fa73.jpg","args":[],"viewport":{"width":800,"height":600}}}'" failed. Exit Code: 1(General error) Working directory: /var/www/local.dev/lets-food-api/public Output: ================ Error Output: ================ ┌────────────────────────────────────────────────────────────┐ │ npm update check failed │ │ Try running with sudo or get access │ │ to the local update config store via │ │ sudo chown -R $USER:$(id -gn $USER) /home/www-user/.config │ └────────────────────────────────────────────────────────────┘ Error: net::ERR_INSECURE_RESPONSE at navigate (/usr/lib/node_modules/puppeteer/lib/Page.js:488:37) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by freekmurze** [comment]
Tested this on another subdomain and it seems to work.

If this is still causing problems, feel free to submit a PR.
