### ISSUE TITLE
Unexpected '?', expecting variable

### ISSUE THREAD

**Issue by dougblackjr** [spatie/browsershot#161]
Getting an error when converting html to a PDF on Ubuntu 16.04 running php 7.1.14

`syntax error, unexpected '?', expecting variable (T_VARIABLE)
File: /var/www/html/directory/vendor/symfony/process/Process.php`

App is running on Slim Framework. Users submit form with CSV, app pulls out variables and injects them into HTML file. Browsershot then converts HTML to PDF via the `->html()` method.

FUNCTION I'M RUNNING:
```
Browsershot::html($html)
			->setDelay(3000)
			->landscape()
			->pages('1')
			->emulateMedia('screen')
			->showBackground()
			->save($this->storage_directory . '/output-' . $this->filename . '.pdf');
```

FULL STACK ERROR:
```
Slim Application Error
The application could not run because of the following error:

Details
Type: ParseError
Message: syntax error, unexpected '?', expecting variable (T_VARIABLE)
File: /var/www/html/lf-certificate-generator/vendor/symfony/process/Process.php
Line: 139
Trace
#0 /var/www/html/lf-certificate-generator/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/l...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#2 /var/www/html/lf-certificate-generator/vendor/spatie/browsershot/src/Browsershot.php(483): spl_autoload_call('Symfony\\Compone...')
#3 /var/www/html/lf-certificate-generator/vendor/spatie/browsershot/src/Browsershot.php(363): Spatie\Browsershot\Browsershot->callBrowser(Array)
#4 /var/www/html/lf-certificate-generator/vendor/spatie/browsershot/src/Browsershot.php(316): Spatie\Browsershot\Browsershot->savePdf('/var/www/html/l...')
#5 /var/www/html/lf-certificate-generator/controller/PdfCreatorController.php(118): Spatie\Browsershot\Browsershot->save('/var/www/html/l...')
#6 /var/www/html/lf-certificate-generator/controller/PdfCreatorController.php(91): PdfCreator->createPdf(Array)
#7 /var/www/html/lf-certificate-generator/index.php(80): PdfCreator->parseData()
#8 [internal function]: Closure->{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#9 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#10 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke(Object(Closure), Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#11 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/App.php(495): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/html/lf-certificate-generator/vendor/slim/slim/Slim/App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/html/lf-certificate-generator/index.php(90): Slim\App->run()
#18 {main}
```

**Comment by freekmurze** [comment]
It's highly unlikely that symfony has a syntax error. Probably you're not running the PHP version you think you are. Please check that this code is running on PHP 7. Make sure you check both the version of PHP running on the cli and the version running web requests.

**Comment by dougblackjr** [comment]
Thanks @freekmurze!
