### ISSUE TITLE
Nagivation Timeout Exceeded

### ISSUE THREAD

**Issue by earthroot** [spatie/browsershot#196]
Hey guys, when I use browsershot in a homestead enviroment works perfectly but when I use it in production on a digitalocean vps ( alongisde the forge instructions for pupeteer) it logs the following:

I call it from a Job, at seemingly random times it works.

```
Exit Code: 1(General error)

Working directory: /var/www/html/springloops

Output:
================


Error Output:
================
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/usr/lib/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>
 in /var/www/html/springloops/vendor/spatie/browsershot/src/Browsershot.php:565
Stack trace:
#0 /var/www/html/springloops/vendor/spatie/browsershot/src/Browsershot.php(384): Spatie\\Browsershot\\Browsershot->callBrowser(Array)
#1 /var/www/html/springloops/app/Jobs/CacheSite.php(56): Spatie\\Browsershot\\Browsershot->bodyHtml()
#2 [internal function]: App\\Jobs\\CacheSite->handle() 
```
Any thoughts?

ps. google took me here: https://github.com/GoogleChrome/puppeteer/issues/2482

**Comment by goper-leo** [comment]
Me too.
