### ISSUE TITLE
I'm having issues with Node & puppeteer any help?

### ISSUE THREAD

**Issue by delino12** [spatie/browsershot#243]
```
"message": "The command \"PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/Users/ekpotoliberty/Stubs/vendor/spatie/browsershot/src/../bin/browser.js' '{\"url\":\"https:\\/\\/google.com\",\"action\":\"screenshot\",\"options\":{\"type\":\"jpeg\",\"path\":\"\\/uploads\\/stubs-1541946055.jpg\",\"quality\":100,\"args\":[],\"viewport\":{\"width\":800,\"height\":600}}}'\" failed.\n\nExit Code: 1(General error)\n\nWorking directory: /Users/ekpotoliberty/Stubs/public\n\nOutput:\n================\n\n\nError Output:\n================\n{ Error: ENOENT: no such file or directory, open '/uploads/stubs-1541946055.jpg'\n  -- ASYNC --\n    at Page.<anonymous> (/usr/local/lib/node_modules/puppeteer/lib/helper.js:144:27)\n    at getOutput (/Users/ekpotoliberty/Stubs/vendor/spatie/browsershot/bin/browser.js:14:40)\n    at callChrome (/Users/ekpotoliberty/Stubs/vendor/spatie/browsershot/bin/browser.js:121:24)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:182:7)\n  errno: -2,\n  code: 'ENOENT',\n  syscall: 'open',\n  path: '/uploads/stubs-1541946055.jpg' }\n",
    "exception": "Symfony\\Component\\Process\\Exception\\ProcessFailedException",
    "file": "/Users/ekpotoliberty/Stubs/vendor/spatie/browsershot/src/Browsershot.php",
    "line": 596,
    "trace": [
        {
            "file": "/Users/ekpotoliberty/Stubs/vendor/spatie/browsershot/src/Browsershot.php",
            "line": 410,
            "function": "callBrowser",
            "class": "Spatie\\Browsershot\\Browsershot",
            "type": "->"
        },
        {
```

**Comment by danhunsaker** [comment]
My guess is the absolute path you're using in your code. There's no `/uploads/` folder, in this case; you almost certainly meant `uploads/`, a path within your project itself.

**Comment by delino12** [comment]
Ok. let me debug this again. Thanks.

**Comment by freekmurze** [comment]
Probably that will be the problem indeed. Feel free to reopen if you're still having problems.

**Comment by delino12** [comment]
@danhunsaker it is still the same issue. error remain the same. Do i need to configure my node modules path inside the Controller?

**Comment by danhunsaker** [comment]
It ... has nothing to do with Node. It's the path you're passing for BrowserShot to write the image to. You have it as absolute, when it needs to be relative. Just remove the leading `/` from that and it should be fine.

**Comment by delino12** [comment]
Yeah, it works. Thanks @danhunsaker @freekmurze
