### ISSUE TITLE
addStyleTag does not work on Windows (10)

### ISSUE THREAD

**Issue by JBtje** [spatie/browsershot#271]
```php
Browsershot::url('https://example.com')
    ->setOption('addStyleTag', json_encode(['content' => 'body{ font-size: 14px; }']))
    ->save($pathToImage);
```

results in:
```
"""
The command "node ^"[REMOVED]^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/exampl ▶

Exit Code: 1(General error)

Working directory: [REMOVED]\public

Output:
================


Error Output:
================
undefined:1
{"url":"https:\/\/example.com","action":"pdf","options":{"args":[],"viewport":{"width":800,"height":600},"addStyleTag":"{\content\:\body{
^

SyntaxError: Unexpected token c in JSON at position 122
at JSON.parse (<anonymous>)
    at Object.<anonymous> ([REMOVED]\vendor\spatie\browsershot\bin\browser.js:3:22)
        at Module._compile (internal/modules/cjs/loader.js:721:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
        at Module.load (internal/modules/cjs/loader.js:620:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
        at Function.Module._load (internal/modules/cjs/loader.js:552:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
        at executeUserCode (internal/bootstrap/node.js:342:17)
        at startExecution (internal/bootstrap/node.js:276:5)
        """
```

Note that is says `"{\content\:`, as in, its trying to escape a "c"?

Adding the following code to `getFullCommand`, prior to `return escapeshellcmd($fullCommand);`
```php
dd('"'.str_replace('"', '\"', (json_encode($command))).'"', escapeshellcmd($fullCommand));
```

Gives:

```
""{\"url\":\"https:\/\/example.com\",\"action\":\"pdf\",\"options\":{\"args\":[],\"viewport\":{\"width\":800,\"height\":600},\"addStyleTag\":\"{\\"content\\":\\"body{ font-size: 14px; }\\"}\"}}" ◀"
```
```
"node ^"Z:^\Dropbox^\Webserver^\www^\Laravel^\DiagnOSAS^\vendor^\spatie^\browsershot^\src/../bin/browser.js^" ^"^{^\^"url^\^":^\^"https:^\/^\/example.com^\^",^\^"action^\^":^\^"pdf^\^",^\^"options^\^":^{^\^"args^\^":^[^],^\^"viewport^\^":^{^\^"width^\^":800,^\^"height^\^":600^},^\^"addStyleTag^\^":^\^"^{^\^\^"content^\^\^":^\^\^"body^{ font-size: 14px^; ^}^\^\^"^}^\^"^}^}^" ◀"
```

**Edit:**
Problem lies with improper escaping of the JSON string that is submitted for `addStyleTag`:
https://github.com/spatie/browsershot/blob/241321f88d7f65868dbe936db910d9012aa98eaa/src/Browsershot.php#L646

**Suggestion:**
Use `base64_encode` on `$command`.

browser.js can easily decode this... and it will make the transmission from PHP to browser.js 'idiot proof', untill a better idiot is invented, that is...

`npm install atob`
```js
var atob = require('atob');
...
args[0] = atob( args[0] )
```

**Comment by mirdic** [comment]
We got the same issue with `Browsershot::headerHtml()` method when `$html` contains `"`.

**Comment by JBtje** [comment]
my current implementation, no time to make a nice PR atm...

**browsershot/src/Browsershot.php**
```php
    // Replace current function with the below code
    protected function getFullCommand( array $command )
    {
        $nodeBinary = $this->nodeBinary ?: 'node';

        $binPath = $this->binPath ?: __DIR__ . '/../bin/browser.js';

        if( strtoupper( substr( PHP_OS, 0, 3 ) ) === 'WIN' ) {
            if( $this->writeOptionsToFile ) {
                $temporaryOptionsFile  = $this->createTemporaryOptionsFile( json_encode( $command ) );
                $wronglyEscapedCommand = '-f '. $temporaryOptionsFile;
            }
            else {
                $wronglyEscapedCommand = json_encode( $command );
            }

            $fullCommand =
                $nodeBinary . ' '
                . escapeshellarg( $binPath ) . ' '
                . '"' . base64_encode( $wronglyEscapedCommand ) . '""';

            return escapeshellcmd( $fullCommand );
        }

        $setIncludePathCommand = "PATH={$this->includePath}";

        $setNodePathCommand = $this->getNodePathCommand( $nodeBinary );

        $optionsCommand = $this->getOptionsCommand( json_encode( $command ) );

        return
            $setIncludePathCommand . ' '
            . $setNodePathCommand . ' '
            . $nodeBinary . ' '
            . escapeshellarg( $binPath ) . ' '
            . $optionsCommand;
    }
```

**browsershot/bin/browser.js**
```js
// Add the below line to the top of the file
var atob = require('atob');

...

const [, , ...args] = process.argv;
args[0] = atob( args[0] ) // ADD THIS LINE, below the above line that already is in the file
```

**Do note:** the above code will most likely only work with Windows. The added line in JS file, will (i think) cause problems on unix/mac.

**Comment by freekmurze** [comment]
Closing this because you've found a solution.

**Comment by Zanzavar** [comment]
Having the same issue on Windows 10 Pro. Any way to fix this to work both for unix and windows?
