### ISSUE TITLE
a strange error

### ISSUE THREAD

**Issue by MostafaRabia** [spatie/browsershot#401]
I have downloaded everything, then i got it

`The command "PATH=$PATH:/usr/local/bin NODE_PATH=/usr/bin/node /usr/bin/npm root -g /usr/bin/node '.../vendor/spat ▶

Exit Code: 1(General error)

Working directory: ...

Output:
================

Error Output:
================
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (.../.../node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (.../.../node_modules/puppeteer/lib/BrowserFetcher.js:26:20)`

it's laravel 5.8, and my code:
`Browsershot::url($url)
		->waitUntilNetworkIdle()
	    ->setScreenshotType('jpeg', 100)
		->setDelay(2000)
		->fullPage()
		->save($file_name.'.jpeg');`

**Comment by bjplink** [comment]
@MostafaRabia Did you ever find a solution for this?

**Comment by MostafaRabia** [comment]
> @MostafaRabia Did you ever find a solution for this?

I forget it 😅

**Comment by BirdyUK** [comment]
@bjplink - did you find a solution? I have the same issue.
