### ISSUE TITLE
TypeError: page.emulateMedia is not a function

### ISSUE THREAD

**Issue by AdiPathak97** [spatie/browsershot#413]
Environment: Ubuntu 16.04
Web Server: Apache

Complete error log:
```
TypeError: page.emulateMedia is not a function
    at callChrome (/var/www/html/my_project/vendor/spatie/browsershot/bin/browser.js:124:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The relevant code in browser.js:
```
if (request.options && request.options.emulateMedia) {
    await page.emulateMedia(request.options.emulateMedia);
}
```

I have called Browsershot using these options:
```
Browsershot::html($pdfBody)
    ->format('A4')
    ->margins($top, $right, $bottom, $left)
    ->emulateMedia('screen')
    ->showBackground()
    ->noSandbox()
    ->timeout(0)
    ->save($localDestination);
```

I did not face this in other environments like CentOS+nginx and in local machine on Windows. I have uninstalled and reinstalled puppeteer to no avail. The only reference to this issue in Puppeteer docs is [puppeteer/puppeteer#395](https://github.com/puppeteer/puppeteer/issues/395) and that was because Author had code from non-master branch, which is clearly not the case here.

Anyone with any idea about making browsershot and puppeteer run in Ubuntu and Apache, please chime in.

**Comment by AdiPathak97** [comment]
#411  I just found this PR, is this the cause of the issue?

**Comment by AdiPathak97** [comment]
I have solved the issue by manually making the change specified in #411 , wonder why npm install didn't fetch the latest commit of master branch as it has already been merged.
