### ISSUE TITLE
Curl Header replacement

### ISSUE THREAD

**Issue by pcm0nk** [spatie/browsershot#414]
I am sending a curl POST request  which then I need to render the htmlpage.After login I get access to curl header and I would like to add the whole header to browsershot so when it visit the page it doesnt get redirected ( the page needs specific headers to be set among with cookie ).
I tried setExtraHttpHeaders but I get this error :
```Symfony\Component\Process\Exception\ProcessFailedException
The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/home/rabter/core/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"https:\/\/www.irantalent.com\/employer\/dashboard","action":"requestsList","options":{"args":[],"viewport":{"width":800,"height":600},"extraHTTPHeaders":{"set-cookie":"access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjY5NGUxZjI5NmU0NzU2OTExM2IxOGU4MjIwZmY0YWMxM2JkMzgyM2JmMzI4M2EyNzhiNTgwY2ZkOTZhMDYyNzI0N2E1YzJiODQ5MTEyNDRlIn0.eyJhdWQiOiIzIiwianRpIjoiNjk0ZTFmMjk2ZTQ3NTY5MTEzYjE4ZTgyMjBmZjRhYzEzYmQzODIzYmYzMjgzYTI3OGI1ODBjZmQ5NmEwNjI3MjQ3YTVjMmI4NDkxMTI0NGUiLCJpYXQiOjE1OTYyODQwMjksIm5iZiI6MTU5NjI4NDAyOSwiZXhwIjoxNjI3ODIwMDI5LCJzdWIiOiI5NzA1MzIiLCJzY29wZXMiOltdfQ.cho8sKzPHkM8gjIBXLpcZzu4a7MUzgh_9t0gbd9YfYlnMY2wwvDCjoCa1z0SLfBR9--WmN4CH89Ydy4k6qbtNzhxTdDFEQa_qqmxfamHwZssI4tTzOIK3odJfozfZNfIUUDGiivRztozl-hPKVbQrZf8NVu4YluE_vn2rG_delovFzafM3MkyUnNdGDPmk2UXg6GXoidrzXFVMhqf3Pb0PcxELZ1XL5XhFVo0W8b1YEbUEW756zxcZ8jX0jIRBVXQpLij0ZS_Ej4rqYSkUW5Ow9lFs6f0C6F3S1pjITW_xH2sI3OVBLRda_u0HPYl44G7G1uNJRBWVxK_fR-59QpY9V9Scy_qJeKCNeRmWQ_WVBFGTM6aKONip0qI2q16vZN-iQs1X-GlfE9BpiFhlAlTnGjdiU-LkhyW26hCkRua56yMIhsOkDo9xQsTS7PHsh-Rl9mp_gZBOi3uOu7FjxjOf-_rLBFTwHKeAgX1-3oaiKnqpTmsjE6yEbTp06xYdiHvn-34dux-8PEeIb6BwVXe-Z6eruqRSJHQmVyxvwCqLFmDCFpitLR02TeVDuMFA2vtvtjIGAuzEPMFDnDvOt4j32-LCor2A3DclLcvBEfp-nVQ38W-dyuslX4FnD22dSfxRGOaxQU0e8EJ_3GOJnRjCGOcyrA0fwZ6KJR8bq2ATw; expires=Sun, 02-Aug-2020 12:13:50 GMT; Max-Age=86400; path=\/; domain=api.irantalent.com"}}}'" failed. Exit Code: 1(General error) Working directory: /home/rabter/core/public Output: ================ Error Output: ================ ┌──────────────────────────────────────────────────────────────┐ │ npm update check failed │ │ Try running with sudo or get access │ │ to the local update config store via │ │ sudo chown -R $USER:$(id -gn $USER) /var/cache/nginx/.config │ └──────────────────────────────────────────────────────────────┘ internal/modules/cjs/loader.js:960 throw err; ^ Error: Cannot find module 'puppeteer' Require stack: - /home/rabter/core/vendor/spatie/browsershot/bin/browser.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15) at Function.Module._load (internal/modules/cjs/loader.js:840:27) at Module.require (internal/modules/cjs/loader.js:1019:19) at require (internal/modules/cjs/helpers.js:77:18) at Object.<anonymous> (/home/rabter/core/vendor/spatie/browsershot/bin/browser.js:1:19) at Module._compile (internal/modules/cjs/loader.js:1133:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10) at Module.load (internal/modules/cjs/loader.js:977:32) at Function.Module._load (internal/modules/cjs/loader.js:877:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) { code: 'MODULE_NOT_FOUND', requireStack: [ '/home/rabter/core/vendor/spatie/browsershot/bin/browser.js' ] }
```
**CURL Post request**
```
 //replace space with + for url encoding
    curl_setopt($ch,CURLOPT_URL,"https://api.irantalent.com/oauth/token");
    curl_setopt($ch,CURLOPT_FOLLOWLOCATION,1);
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
  $headers = [];
// this function is called by curl for each header received
curl_setopt($ch, CURLOPT_HEADERFUNCTION,
  function($curl, $header) use (&$headers,&$wholeheader)
  {
    $len = strlen($header);
    $header = explode(':', $header, 2);
    if (count($header) < 2) // ignore invalid headers
      return $len;
    $headers[strtolower(trim($header[0]))][] = trim($header[1]);

    return $len;

  }

);
  curl_setopt($ch,CURLOPT_POST,1);
    curl_setopt($ch,CURLOPT_POSTFIELDS,$postFields);
    curl_setopt($ch,CURLOPT_COOKIEJAR,"cookie.txt");
    $response = json_decode(curl_exec($ch));

```

The header is an array :
```
array:16 [▼
  "server" => "nginx;nginx/1.14.2"
  "content-type" => "application/json; charset=UTF-8;text/html; charset=utf-8"
  "transfer-encoding" => "chunked"
  "vary" => "Accept-Encoding;Accept-Encoding"
  "set-cookie" => "access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImQ5ZTVlODk2N2I3OTRkYWJjODYxNzcwMTU5ODhiZjcyYWU3ZjI0NDUxOGRmNGFmZDVmMjkyYTNjY2U2MTY5ZTUyMWQ5YjY2MjliOTY ▶"
  "pragma" => "no-cache"
  "cache-control" => "no-store, private"
  "date" => "Sat, 01 Aug 2020 12:25:58 GMT;Sat, 01 Aug 2020 12:26:01 GMT"
  "x-ratelimit-limit" => "60"
  "x-ratelimit-remaining" => "59"
  "access-control-allow-origin" => "*"
  "access-control-allow-methods" => "POST,GET,OPTIONS,PUT,DELETE,PATCH"
  "access-control-allow-headers" => "Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With,Accept,X-XSRF-TOKEN"
  "content-length" => "521226"
  "x-powered-by" => "Express"
  "etag" => "W/"7f40a-Pg9HKR0vPHZdHPRI4+bJEDUlWKY""
]
```
I would like to add this header into my browsershot request so it can access the protected page. 
How Can I achieve this with or without setExtraHttpHeaders  ?
Thanks

**Comment by freekmurze** [comment]
`Error: Cannot find module 'puppeteer'` makes me think there is something wrong with the environment where you execute the command in. Make sure all necessary dependancies are available.
