### ISSUE TITLE
How to import local image path to generate pdf ?

### ISSUE THREAD

**Issue by Hazelwu2** [spatie/browsershot#416]
Hello,
I using spatie/browsershot to generate pdf is very well.
but I want to import my local image into HTML and generate pdf, have some problem.

if I using outsite domain like this(https://upload.wikimedia.org/wikipedia/zh/1/1e/ROC_ID_2005_specimen_front.jpg)  is work.
when I using local path like this (http://localhost/uploads/images/identity_card_front/2aF9FQRImRVbO0QvZycOWWEYb3P7VnLS1elwdHkD.png) is not work. 

This is work. because I read outsite domain image.
`    
Browsershot::url('https://img.ltn.com.tw/Upload/food/page/2019/11/22/191122-9862-1-NjB3U.jpg')->save('example2.pdf');
`

This is not work. I import my image from localhost, and I'm sure my image path is correct. 
`
Browsershot::url('http://localhost/uploads/images/apple.png')->save('example.pdf');
`

**Below is the error message.**
`[2020-08-15 09:50:47] production.ERROR: The command "PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/tody_website/vendor/spatie/browsershot/src/../bin/browser.js' '{"url":"file:\/\/\/tmp\/1726216647-0860196001597456246\/index.html","action":"pdf","options":{"path":"uploads\/pdf\/contract\/1597456246.pdf","args":[],"viewport":{"width":800,"height":600},"displayHeaderFooter":true,"format":"A4","headerTemplate":"<div style=\"font-size:12pt; text-align: center; height:25.4mm;\"><\/div>\n","footerTemplate":"<div style=\"font-size:12pt; text-align: center; height:25.4mm;\"><\/div>\n","margin":{"top":"25.4mm","right":"31.8mm","bottom":"31.8mm","left":"25.4mm"},"timeout":15000,"waitUntil":"networkidle0"}}'" failed.

Exit Code: 1(General error)

Working directory: /var/www/tody_website/public

Output:
================

Error Output:
================
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/var/www/tody_website/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/tody_website/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:48:39)
 {"exception":"[object] (Symfony\\Component\\Process\\Exception\\ProcessFailedException(code: 0): The command \"PATH=$PATH:/usr/local/bin NODE_PATH=`npm root -g` node '/var/www/tody_website/vendor/spatie/browsershot/src/../bin/browser.js' '{\"url\":\"file:\\/\\/\\/tmp\\/1726216647-0860196001597456246\\/index.html\",\"action\":\"pdf\",\"options\":{\"path\":\"uploads\\/pdf\\/contract\\/1597456246.pdf\",\"args\":[],\"viewport\":{\"width\":800,\"height\":600},\"displayHeaderFooter\":true,\"format\":\"A4\",\"headerTemplate\":\"<div style=\\\"font-size:12pt; text-align: center; height:25.4mm;\\\"><\\/div>\
\",\"footerTemplate\":\"<div style=\\\"font-size:12pt; text-align: center; height:25.4mm;\\\"><\\/div>\
\",\"margin\":{\"top\":\"25.4mm\",\"right\":\"31.8mm\",\"bottom\":\"31.8mm\",\"left\":\"25.4mm\"},\"timeout\":15000,\"waitUntil\":\"networkidle0\"}}'\" failed.

Exit Code: 1(General error)

Working directory: /var/www/tody_website/public

Output:
================

Error Output:
================
internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The \"original\" argument must be of type function
    at promisify (internal/util.js:209:11)
    at Object.<anonymous> (/var/www/tody_website/node_modules/extract-zip/index.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/tody_website/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:48:39)
 at /var/www/tody_website/vendor/spatie/browsershot/src/Browsershot.php:738)
[stacktrace]
#0 /var/www/tody_website/vendor/spatie/browsershot/src/Browsershot.php(543): Spatie\\Browsershot\\Browsershot->callBrowser(Array)
#1 /var/www/tody_website/vendor/spatie/browsershot/src/Browsershot.php(482): Spatie\\Browsershot\\Browsershot->savePdf('uploads/pdf/con...')
#2 /var/www/tody_website/app/Services/PdfService.php(246): Spatie\\Browsershot\\Browsershot->save('uploads/pdf/con...')
#3 /var/www/tody_website/app/Http/Controllers/ContractController.php(314): App\\Services\\PdfService::draw(9)
#4 /var/www/tody_website/app/Http/Controllers/ContractController.php(139): App\\Http\\Controllers\\ContractController->addOrEditSubletHouse(Object(Illuminate\\Http\\Request), Object(App\\Models\\Contract))
#5 [internal function]: App\\Http\\Controllers\\ContractController->addContract(Object(Illuminate\\Http\\Request), 'subletHouse')
#6 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#7 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('addContract', Array)
#8 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\ContractController), 'addContract')
#9 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#10 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#11 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/tody_website/app/Http/Middleware/CheckUserSession.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\CheckUserSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle(Object(Illuminate\\Http\\Request), Object(Closure), 60, '1')
#20 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#23 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#24 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#25 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#26 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#27 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/tody_website/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/tody_website/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/tody_website/vendor/`

I find for all related questionns but I didn't get any results. 
How to import  local image path, have any ideas ?
Thanks!

**Comment by Hazelwu2** [comment]
Hi, Finally I resolve problem. I get my local image and then I tranfer to Base64 format.
Basically, it cannot read local image because security measure, so access to local images is blocked. 
**So, local image transfer to Base64 format or local image to upload to S3 is a good solution.** 
[Reference](https://github.com/puppeteer/puppeteer/issues/1643)

`$a = public_path('uploads/images/test/2aF9FQRImRVbO0QvZycOWWEYb3P7VnLS1elwdHkD.png');
$c = file_get_contents($a);
$d = base64_encode($c);
$e = 'data:image/jpg;base64,'.$d;
$f = '<img src="'. $e.'" />';
Browsershot::html($f)
    ->timeout(5)
    ->save('example.pdf');
return $f;`
