### ISSUE TITLE
 Error: Request is already handled!

### ISSUE THREAD

**Issue by HoangNK93** [spatie/browsershot#434]
I run a batch job in Laravel8 to get information from several websites. I also used `useCookies` and `setOption('addScriptTag', json_encode(['content' => $js]))`. I checked server logs and saw this error:
```
Error Output:
================
(node:155968) UnhandledPromiseRejectionWarning: Error: Request is already handled!
    at Object.exports.assert (/var/www/html/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at HTTPRequest.continue (/var/www/html/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:217:21)
    at /var/www/html/vendor/spatie/browsershot/bin/browser.js:97:37
    at /var/www/html/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/var/www/html/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Page.emit (/var/www/html/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at /var/www/html/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:164:100
    at /var/www/html/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
(node:155968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:155968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:155968) UnhandledPromiseRejectionWarning: Error: Request is already handled!
```

How can I fix this?

**Comment by bogdanovmaxim87** [comment]
Try to update your nodejs to 12.x version.
