### ISSUE TITLE
`setWSEndpoint` does not work with `Browsershot::html` (only `::url`)

### ISSUE THREAD

**Issue by alfredbez** [spatie/browsershot#499]
This does not work:
```php
Browsershot::html('<h1>It works!</h1>')->setWSEndpoint('wss://chrome.browserless.io');
```

But this does:
```php
Browsershot::url('https://www.google.com')->setWSEndpoint('wss://chrome.browserless.io');
```

---

If I try to run the script myself it outputs the following error:
```
/home/abez/projects/privat/mysideproject/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: Protocol error: Connection closed. Most likely the page has been closed.
    at Object.assert (/home/abez/projects/privat/mysideproject/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at Page.close (/home/abez/projects/privat/mysideproject/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1193:21)
    at callChrome (/home/abez/projects/privat/mysideproject/vendor/spatie/browsershot/bin/browser.js:267:28)
```

**Comment by freekmurze** [comment]
Feel free to PR a fix for this.

**Comment by jmslbam** [comment]
@alfredbez Browserless doesn't accept HTML via Post last time I checked, but please do double-check it with this SaaS. And if so, maybe checkout https://github.com/spatie/browsershot/pull/496 if it does.
